### PR TITLE
Channel-Picker

### PR DESCRIPTION
**Pull request by MarkusTheOrt**
Spotlight like search for all channels when in fullscreen. 
Adds Feature #4

### CODE REVIEW

**Comment by MarkusTheOrt** [comment]
I am quite Unsure if I should get drivers info by just adding it locally (i.e. drivers.js) or if I should get it via  XHR (as its done in channel-picker.js:95)

**Comment by maartenflippo** [comment]
Yes I was debating that one myself as well. What would probably work best is to get them from the HTML in order to account for driver changes etc. Then we could augment this data with some static data we provide ourselves, but at least the basic information will always be in sync with the rest of the page.

Some ideas I would like to see visually:
* Driver full name
* Team name and maybe logo

**Comment by MarkusTheOrt** [comment]
### Features

* Select a channel from any available one while in fullscreen
* Search for your preferred channel

[Video-Thumbnail](https://youtu.be/GlNIfznLWis)
Preview

**Comment by maartenflippo** [comment]
Amazing, it looks very good! Thank you for the effort.

**Pull request merged**
