### PR TITLE
Camera Overlay is now more like a video title

### PR DESCRIPTION
**Pull request by MarkusTheOrt**
Screenshot

I've made slight additions to the layout.css file of yours to make the current watching Camera an overlay on the Video. The current Camera automatically hides once the players UI hides - this is handled using the utils.js I've added.

### CODE REVIEW

**Comment by maartenflippo** [comment]
Oh that is a very good idea. More space for the player is always better. One change I would like to see is to scope these changes to the `._2c4cB` class, just as the rest of the style modifications. The reason for this is because if the website gets updated and these generated class names change, we can be more certain the extension won't break the UI.

**Comment by MarkusTheOrt** [comment]
I guess that's fair. Im doing that tomorrow.

**Comment by MarkusTheOrt** [comment]
okay I'll changed it now - using the selectors you already made :-) 👍

**Comment by maartenflippo** [comment]
@MarkusTheOrt thanks for the contribution!

**Pull request merged**
