### PR TITLE
Add ability to skip forward/backward 5 seconds with right/left arrow keys.

### PR DESCRIPTION
**Pull request by bfayers**
Does what it says on the title.

### CODE REVIEW

**Comment by maartenflippo** [comment]
Thank you very much for this pull request, this is indeed also a feature I want in the extension. One question I have is do you know how this behaves during a live feed. Of course skipping time there is not supported but I wonder whether this has unintended side-effects.

**Comment by bfayers** [comment]
@maartenflippo 
I will test the interaction in the next live session I can, if it does cause some side effects (If any I expect it on the skip forward function when already caught up to "live") I may add a check in for live sessions and just disable the skip function from working in them.

**Comment by maartenflippo** [comment]
Great, let me know what the outcome will be.

**Comment by bfayers** [comment]
@maartenflippo Just tested this during the "High Speed Test" and skipping backwards works fine, so does skipping forwards however if you are already "caught up" you will get a few seconds of the buffering logo and then back to normal.

**Pull request merged**
